<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(ManagedPath)\UnityEngine.UIModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(ManagedPath)\Unity.TextMeshPro.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
